name: Deploying to EB
on:
 push:
   branches:
     - feature-*

  
jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
    - name: check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Installing Libraries
      run: |
          pip install flake8
    - name: Lint with flake8
      run: |
           # Select identifies which errors should cause the job to fail
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
           # The exit zero flag will show errors as warnings and not fail the run
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


 build:
  runs-on: ubuntu-latest
  needs: lint
  steps: 
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
          python-version: 3.8
    - name: Installing Libraries
      run: |
            
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
    - name: create zip bundle
      run: | 

          zip -r deploy_package.zip ./
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-east-1"

    - name: Upload package to S3 bucket
      run: aws s3 cp deploy_package.zip s3://githubtestbucket/

    - name: Create new ElasticBeanstalk Application Version
      run: |
          aws elasticbeanstalk create-application-version \
          --application-name my-awesome-app \
          --source-bundle S3Bucket="githubtestbucket",S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"
    - name: Deploy new ElasticBeanstalk Application Version
      run: aws elasticbeanstalk update-environment --environment-name my-awesome-environment --version-label "ver-${{ github.sha }}"