name: Deploying to EB
on:
 push:
   branches:
     - feature-*

  
jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
    - name: check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Installing Libraries
      run: |
          cd bad
          pip install flake8
    - name: Lint with flake8
      run: |
           # Select identifies which errors should cause the job to fail
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
           # The exit zero flag will show errors as warnings and not fail the run
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


 build:
  runs-on: ubuntu-latest
  needs: lint
  steps: 
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
          python-version: 3.8
    - name: Installing Libraries
      run: |
          cd bad
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
    - name: create zip bundle
      run: | 
          cd bad
          zip -r ../${{ github.sha }}.zip .
    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: zipped-bundle
        path: ${{ github.sha }}.zip
           
 deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
  -  name: checkout code
     uses: actions/checkout@v2
  -  name: Set up Python
     uses: actions/setup-python@v2
     with: 
        python-version: 3.8
  -  name: Install Elastic Bean CLI
     run: |
           python -m pip install --upgrade pip 
           pip install awsebcli --upgrade
           eb --version
  -  name: Download artifact
     uses: actions/download-artifact@v2
     with:
       name: zipped-bundle
  -  name: Deploy to EB
     uses: einaregilsson/beanstalk-deploy@v20
     with: 
       aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
       aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
       application_name: githubactionsapplication
       environment_name: Githubactionsapplication-env
       version_label: 1.0
       region: "us-east-2"
       deployment_package: ${{ github.sha }}.zip